### PR TITLE
Fix database not beeing written to production terraform config

### LINKED ISSUE #775: Fix tests when running with terraform 1.1
When running tests on a system with terraform 1.1, they fail with a missing provider error.

### PR DESCRIPTION
**Pull request by jvasseur**
This will also fix #775

### CODE REVIEW

File: generators/utils/database/index.ts [hunk 1]
```diff
@@ -29,7 +29,11 @@ class DatabaseUtilGenerator extends BaseGenerator<DatabaseUtilGeneratorOptions>
 
         this.prependTemplate('provision.yaml.ejs', `ansible/packages/${packageName}/provision.yaml`, { packageName });
 
-        if (this.existsDestination('terraform/common/database') && this.existsDestination('terraform/production')) {
+        if ([
+            'terraform/common/database/main.tf',
+            'terraform/common/database/outputs.tf',
+            'terraform/production/outputs.tf',
+        ].every(this.existsDestination.bind(this))) {
```
Comment (jvasseur) [inline generators/utils/database/index.ts:36]: The previous code didn't work because `existsDestination` only works for files and not directories.

Comment (jvasseur) [inline generators/utils/database/index.ts:36]: The previous code didn't work because `existsDestination` only works for files and not directories.
